Revert "Revert image pinning to `2.1.1`"
github/codespaces-jupyter pull request #28
Opened 2023-01-27 10:08 UTC by 1710199225101962

Reverts github/codespaces-jupyter#14

2023-01-27 11:16 UTC, 1710199225101962 commented
> прокомментировал

Походу все, не скидывается

2023-02-02 02:27 UTC, aUsABuisnessman commented
Modal rocket has lift

2023-02-02 03:53 UTC, Molecule24 approved these changes

2023-02-02 03:54 UTC, Molecule24 requested changes
Codespace node

2023-02-16 18:47 UTC, closed without merging